config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get('/about', {to:'about#index'})
  get('/contact', {to:'contact#index'})

  post('/contact', {to:'contact#create', as:'contact_submit'})

#   delete '/questions/:id', to:'questions#destroy'
#   (HTTP Verb: get - path: /questions/:id/edit ) ==> questions controller / edit action
#   get '/questions/:id/edit', to:'questions#edit'
# (HTTP Verb: get - path: /questions/:id ) ==> questions controller / show action
#   get '/questions/:id', to:'questions#show'
# (HTTP Verb: post - path: /questions/:id/comments ) ==> comments controller / create action
#   post '/questions/:id/comments', to:'comments#create'
# (HTTP Verb: get - path: /faq ) ==> home controller / faq action
#   get '/faq', to:'home#faq'
  resources :products do
    resources :favourites, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy], shallow: true  do
      resources :likes, only: [:create, :destroy]
      resources :votes, only: [:create, :destroy, :update]
    end
  end

  resources :tags, only: [:index, :show]


  # resources :reviews, only: :none do
  #   resources :likes, only: [:index, :create, :destroy]
  # end
  #


  resources :users, only:[:new, :create] do
    resources :favourites, only: [:index]
  end
  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
    #password does not show in the address url
  end
  get('/admin/dashboard', {to: 'admin/dashboard#index'})
  # get('/products/new', {to: 'products#index', as:'products'})

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products, only:[:index, :show, :create] do
        resources :reviews, only:[:create]
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews
  belongs_to :user
  has_many :favourites, dependent: :destroy
  has_many :user_favourite_it, through: :favourites, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates(:title, { presence: true, uniqueness: true, exclusion: { in: %w( Apple Software Sony),message: "%{value} is reserved." }})
  #validates the title to be true, unique and not the reserved words
  validates(:price, { presence: true, numericality: { greater_than_or_equal_to: 0 }})
  validates(:description, {presence: true})
  validates(:sale_price, { presence:true, numericality: { less_than_or_equal_to: :price}})

  validate :description_length

  after_initialize :set_defaults
  before_validation :capitalize_title

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  mount_uploader :image, ImageUploader

  def self.search(arg1, arg2)
    where(["title ILIKE ? OR description ILIKE ?", "%#{arg1}%", "%#{arg2}%"]).order(:description, :title)
    #(['description ILIKE ?', "%#{arg2}%"], ['title ILIKE ?', "%#{arg2}%"])

  end

  def favourite_by?(user)
    favourites.exists?(user: user)
  end

  def favourite_for(user)
    favourites.find_by(user: user)
  end

  private

  def description_length
    if(description.present? && description.length < 10)
      errors.add(:description, 'description is shorter than 10 characters')
    end
  end

  def set_defaults
    self.price ||= 1
    self.sale_price ||= price
  end

  def capitalize_title
    self.title = title.capitalize if title.present?

  end

end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
  before_action :authenticate_user
  skip_before_filter :verify_authenticity_token

  def index
    @products = Product.last(20)
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params.require(:product).permit(:title, :description, :price))
    @product.user = @user
    if @product.save
      render json: @product
    else
      render json: @product.errors.full_messages, status: 500
    end
  end

  private
  def authenticate_user
    @user = User.find_by_api_token params[:api_token]
    head :unauthorized if @user.blank?
  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @product = Product.new
  end

  def index
    @products = Product.last(20)
  end

  def create
    # product_params = params.require(:product).permit([:title, :description, :price])
    @product = Product.new(params.require(:product).permit(:title, :description, :price, :category_id, :image))
    @product.user = current_user
    if @product.save
      flash[:notice] = "New product created"
      ProductsMailer.notify_product_owner(@product).deliver_now
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find params[:id]
    @review = Review.new
  end

  def edit
    @product = Product.find params[:id]
    redirect_to root_path, alert:'access denied' unless can? :edit, @product
  end

  def update

    @product = Product.find params[:id]
    product_params = params.require(:product).permit([:title, :description, :price, :category_id, { tag_ids:[] }, :image])
    # if @product.update(product_params)
    #   redirect_to product_path(@product)
    # else
    #   render :edit
    # end
    if !(can? :edit, @product)
      redirect_to root_path, alert:'access denied'
    elsif @product.update(product_params.merge({slug: nil}))
      redirect_to product_path(@product)
    else
      render :edit
    end
  #   # if @product.user != current_user
  #   #   flash[:alert] = "You cannot change a product that you did not create"
  #   #   redirect_to product_path(@product)
  #   # elsif @product.update(product_params)
  #   #   redirect_to product_path(@product)
  #   # else
  #   #   render :edit
  #   # end
  #   # You CAN'T change a product that you did not create
  end

  def destroy
    if !(can? :destroy, @product)
      redirect_to root_path, alert:'access denied'
    else
      product = Product.find params[:id]
      product.destroy
      redirect_to products_path
    end
  end

end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= form_for @product do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.text_area :price %>
  </div>

  <div>
    <%= f.label :category_id %>
    <%= f.text_area :category_id %>
  </div>

  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h3 style="text-align:center;">All Products</h3></div>

  <table class="table table-hover table-bordered">
    <thead class="thead-inverse">
      <tr>
        <th>Product</th>
        <th>Own By</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.title, product_path(product) %></td>
        <td><%= product.user.first_name %></td>

      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= @product.errors.full_messages.join(', ') %>

<div class="col-md-6">
  <%= form_for @product do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">

      <span>Category:</span>
      <%= f.collection_select :category_id, Category.all, :id, :name, class: "form-control"%>
    </div>


    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_area :price, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.collection_select :tag_ids, Tag.order(:name), :id, :name,
                              {},
                              { multiple: true, class:'form-control chosen-select'}%>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
    <%= f.submit %>
  <% end %>

</div>

app/views/products/show.html.erb
<h1>Title: <%= @product.title %></h1>
<p>Description: <%= @product.description %><p>
<p>Price: <%= @product.price %><p>
<p>Category: <%= @product.category_id %></p>
<p>Owner: <%= @product.user.first_name %></p>
<p><%= image_tag @product.image.url(:medium) if @product.image.present? %></p>

<p>Tag(s): <% @product.tags.each do |t| %>
  <%= link_to t.name, tag_path(t) %>
<% end %>
</p>


<% if user_signed_in? && (can? :favourite, @product)%>
  <% if !@product.favourite_by?(current_user) %>
    <%= link_to fa_icon("thumbs-o-up"), product_favourites_path(@product), method: :post%>
  <% else %>
    <%= link_to fa_icon("thumbs-up"),  product_favourite_path(@product, @product.favourite_for(current_user)), method: :delete %>
    <span><%= pluralize(@product.favourites.count, 'favourite') %></span>
  <% end %>
<% end %>


<% if can? :edit, @product%>
  <%= link_to 'Edit', edit_product_path(@product) %>
<% end %>

<%# Rails enables us to make links end non-GET requests by setting the `method`
    attribute for `link_to`. Rails uses Javascript to accomplish that. %>
<% if can? :destroy, @product%>
  <%= link_to 'Delete', product_path(@product), method: :delete, data:{confirm: 'Are you sure?'} %>
<% end %>
<hr>

<%# @review.errors.full_messages.join(', ') %>

<h2>Reviews</h2>
<%= form_for [@product, @review] do |f| %>
  <p>Comment:</p>
  <%= f.text_area :body, {class: "form-control"} %>
  <p>Rating:</p>
  <%# f.text_area :rating %>
  <%= f.select :rating, [1,2,3,4,5] %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

<hr>
<% @product.reviews.each do |r| %>

  <p><%= r.body  %></p>
  <p><%= r.user.first_name %></p>
  <p>Rating: <%= r.rating %></p>
  <p><%= r.body %></p>


  <% if user_signed_in? && (can? :like, r)%>
    <% if !r.liked_by?(current_user) %>
      <%= link_to fa_icon("heart-o"), review_likes_path(r), method: :post%>
    <% else %>
      <%= link_to fa_icon("heart"), like_path(r.like_for(current_user)), method: :delete %>
      <span><%= pluralize(r.likes.count, 'like') %></span>
    <% end %>
  <% end %>

  <% if user_signed_in? && (can? :vote, r)%>
    <% user_vote = r.votes.find_by_user_id current_user %>
    <% if user_vote.nil? %>
      <%= link_to fa_icon('thumbs-o-up'), review_votes_path(r, {is_up: true}), method: :post %>
      <%= link_to fa_icon('thumbs-o-down'), review_votes_path(r, {is_up: false}), method: :post %>
    <% elsif user_vote.is_up?%>
      <%= link_to fa_icon('thumbs-up'), vote_path(user_vote), method: :delete %>
      <%= link_to fa_icon('thumbs-o-down'), vote_path(user_vote, {is_up: false}), method: :patch %>
    <% else %>
      <%= link_to fa_icon('thumbs-o-up'), vote_path(user_vote, {is_up: true}), method: :patch %>
      <%= link_to fa_icon('thumbs-down'), vote_path(user_vote), method: :delete %>
    <% end %>
  <% end %>

  <%= r.votes_count %>



  <% if can? :destroy, r%>
    <%# link_to 'Delete review', product_review_path(@product, r), method: :delete, data:{confirm: "Are your sure?"} %>
    <%= link_to 'Delete review', review_path(r), method: :delete, data:{confirm: "Are your sure?"} %>
  <% end %>

  <hr>



<% end %>